project:
  type: website
  output-dir: docs

website:
  title: "Biostatistics M238"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: homework2.qmd
        text: Homework 2
      - href: homework3.qmd
        text: Homework 3

format:
  html:
    theme: cosmo
    toc: true

execute:
  echo: true
  warning: false
  message: false